"""empty message

Revision ID: 0454138e3d18
Revises: 3a0a7be660ed
Create Date: 2024-08-23 15:20:57.541024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0454138e3d18'
down_revision = '3a0a7be660ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accommodation_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_comments_accommodations_id_accommodations', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comments_accommodation_id_accommodations'), 'accommodations', ['accommodation_id'], ['id'])
        batch_op.drop_column('accommodations_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accommodations_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_comments_accommodation_id_accommodations'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comments_accommodations_id_accommodations', 'accommodations', ['accommodations_id'], ['id'])
        batch_op.drop_column('accommodation_id')

    # ### end Alembic commands ###
