"""empty message

Revision ID: 508fc00a018b
Revises: 0454138e3d18
Create Date: 2024-09-14 19:55:25.838453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508fc00a018b'
down_revision = '0454138e3d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_accommodation_id', ['accommodation_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_accommodation_id', type_='unique')

    # ### end Alembic commands ###
