"""add email column

Revision ID: 5be7353d5046
Revises: 0231e581bee1
Create Date: 2024-10-27 14:41:08.835981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be7353d5046'
down_revision = '0231e581bee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_accommodations_category_id_categories', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_accommodations_category_id_categories'), 'categories', ['category_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String()))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR())
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR())
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('email')

    with op.batch_alter_table('accommodations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_accommodations_category_id_categories'), type_='foreignkey')
        batch_op.create_foreign_key('fk_accommodations_category_id_categories', 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###
